name: Test

on:
  pull_request:
    branches: [ main ]

jobs:

  linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
    steps:
      -
        name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      -
        uses: actions/checkout@v2
      -
        name: dependencies
        run: |
          python -m pip install poetry
          poetry install
      -
        name: install hooks
        run: poetry run pre-commit install-hooks
      -
        name: flake8
        run: poetry run pre-commit run flake8 --all-files --show-diff-on-failure
      -
        name: pylint
        run: poetry run pre-commit run pylint --all-files --show-diff-on-failure
      -
        name: mypy
        run: poetry run pre-commit run mypy --all-files --show-diff-on-failure

  tests:
    runs-on: ubuntu-latest
    needs:
      - linters
    env:
      SOURCES_DIR: sources
    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
    steps:
      -
        name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
            python-version: ${{ matrix.python-version }}
      -
        uses: actions/checkout@v2
      -
        name: Install dependencies
        run: |
          python -m pip install poetry
          poetry install
      -
        name: pytest
        run: poetry run pytest -vv
